name = "Sport Zone"
description = "# Sport Zone-comércio De Artigos Desportivos Sa"
license = "MIT"
homepage = "https://connora13121212.github.io/rsportline/"
min_version = "0.17.0"
demo = "https://connora13121212.github.io/rsportline/"

[extra]


[author]
name = "Vincent Prouillet"
homepage = "https://connora13121212.github.io/rsportline/"

[original]
author =  "comfusion"
homepage = "https://connora13121212.github.io/rsportline/"
repo = "https://connora13121212.github.io/rsportline/"
